[package]
name = "dir-reconstruct"
version = "0.1.0"
edition = "2021"

[profile.release]
debug=true

[dependencies]
anyhow = "1.0.86"
itertools = "0.13.0"
tokio = { version = "1.39.3", features = ["full"] }

